# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy source code
COPY src ./src

# Expose standard IO for MCP
# No ports required; uses stdio

# Default command
CMD ["node", "src/index.js"]
